//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Proyecto.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_PHYSICAL_MEM                101
#define IDS_PARAMETROSHT_CAPTION        102
#define IDC_DISK_SPACE                  107
#define IDD_ENLACEPAGE1                 109
#define IDD_ENLACEPAGE2                 110
#define IDS_ENLACESHT_CAPTION           112
#define IDD_PROGRESS                    116
#define IDS_PROGRESS_CAPTION            117
#define IDS_INTERACCOBSSHT_CAPTION      122
#define IDD_INTERACCOBSERVADAPAGE1      123
#define IDD_INTERACCOBSERVADAPAGE2      124
#define CG_IDS_PHYSICAL_MEM             125
#define CG_IDS_DISK_SPACE               126
#define CG_IDS_DISK_SPACE_UNAVAIL       127
#define IDR_MAINFRAME                   128
#define IDR_PROYECTYPE                  129
#define IDD_ANGULO                      130
#define IDD_RECTA                       131
#define IDR_3DTOOLBAR                   132
#define IDB_SPLASH                      133
#define IDR_ANILLOFENIL                 135
#define IDR_BIFENIL                     136
#define IDR_TRIFENIL                    137
#define IDR_CHILDFRAME                  138
#define IDB_MAINFRAMEBAR                140
#define IDD_LIST                        143
#define IDD_EJE                         147
#define IDD_3DDATA                      148
#define IDD_ICONOS                      151
#define IDI_ANILLOFENIL                 152
#define IDI_BIFENIL                     153
#define IDI_TRIFENIL                    154
#define IDC_CURSORAF                    159
#define IDC_CURSORBF                    165
#define IDC_CURSORTF                    168
#define IDD_INTERACC                    170
#define IDD_INTERACCCOMPONENTS          171
#define IDD_PARAMVARIABLEPAGE1          173
#define IDD_LISTCTRL                    174
#define IDI_PARAM                       175
#define IDI_INTERACC                    176
#define IDI_TENSOR                      177
#define IDD_PARAMETROPAGE1              184
#define IDD_PARAMETROPAGE2              185
#define IDC_CURSOR1                     190
#define IDD_PROPIEDADES                 191
#define IDD_DIALOG1                     194
#define IDD_ENLACEPAGE3                 196
#define IDD_LISTCTRL2                   197
#define IDD_PREFERENCIASPAGE1           200
#define IDD_INTERACCELEGIDASPAGE1       201
#define IDD_INTERACCELEGIDASPAGE2       202
#define IDB_ANILLOFENIL                 205
#define IDB_BIFENIL                     206
#define IDB_TRIFENIL                    207
#define IDC_CURSORDRAG                  209
#define IDB_MINIANILLO                  210
#define IDB_MINIBIFENIL                 211
#define IDB_MINITRIFENIL                212
#define IDB_EJEANILLOFENIL              213
#define IDB_EJEBIFENIL                  214
#define IDB_EJETRIFENIL                 215
#define IDD_PREFERENCIASPAGE2           219
#define IDD_PREFERENCIASPAGE3           220
#define IDB_TRIFENILAVERTURA            223
#define IDC_VALOR                       1001
#define IDC_ESTADO                      1002
#define IDC_INICIO                      1003
#define IDC_LIST_STATIC                 1003
#define IDC_PROGDLG_PROGRESS            1003
#define IDC_ETQTPARAM                   1003
#define IDC_FIN                         1004
#define IDC_LIST_ELIMINAR               1004
#define IDC_PROGDLG_PERCENT             1004
#define IDC_INCREMENTO                  1005
#define IDC_LIST_ACTIVAR                1005
#define IDC_IMAGEN                      1006
#define IDC_LONGITUD                    1007
#define IDC_TETA                        1008
#define IDC_PHI                         1009
#define IDC_LONGITUD2                   1010
#define IDC_X1                          1011
#define IDC_LIST_LIST1                  1011
#define IDC_TETA2                       1011
#define IDC_X2                          1012
#define IDC_Y1                          1013
#define IDC_Y2                          1014
#define IDC_Z1                          1015
#define IDC_Z2                          1016
#define IDC_ANG_ELEGIDO                 1016
#define IDC_LADO_ELEGIDO                1017
#define IDC_LADOS                       1017
#define IDC_ENLACE_ELEGIDO              1018
#define IDC_TIPO                        1019
#define IDC_PHI2                        1020
#define IDC_ANGULO_ROTACION             1021
#define IDC_CARA_FRONTAL                1023
#define IDC_CARA_POSTERIOR              1024
#define IDC_VALOR_EJEX                  1025
#define IDC_VALOR_EJEY                  1027
#define IDC_VALOR_EJEZ                  1028
#define IDC_ZOOM                        1029
#define IDC_ANG_PERSPECTIVA             1031
#define IDC_ROTAR_EJEX                  1032
#define IDC_ETQTPOLO1                   1033
#define IDC_ETQTPOLO2                   1034
#define IDC_ROTAR_EJEY                  1035
#define IDC_INTRCBASE                   1035
#define IDC_ROTAR_EJEZ                  1036
#define IDC_ETIQUETA                    1037
#define IDC_LIST1                       1044
#define IDELIMINAR                      1046
#define IDNUEVO                         1047
#define IDGUARDAR                       1048
#define IDC_LIST                        1049
#define IDC_ETQT                        1060
#define IDC_PARAMETRO                   1061
#define IDC_ACTUAL                      1083
#define IDC_TITULO                      1084
#define IDC_ASUNTO                      1085
#define IDC_CREADOR                     1086
#define IDC_DESCRIPCION                 1087
#define IDC_NOMBREPROY                  1088
#define IDC_ANTERIORES                  1088
#define IDC_CARPETA                     1089
#define IDC_SIGUIENTES                  1089
#define IDC_INTA                        1089
#define IDC_INTB                        1090
#define IDC_INTC                        1091
#define IDC_UNID_DISTANCIA              1093
#define IDC_RADIO2                      1094
#define IDC_UNID_ANGULO                 1095
#define IDC_UNID_INTERACC               1096
#define IDC_SIMETRIA                    1097
#define IDC_RADIO3                      1098
#define IDC_SELECC1                     1104
#define IDC_SELECC2                     1105
#define IDC_SELECC3                     1106
#define IDC_PLANO                       1107
#define IDC_TZZ                         1108
#define IDC_TXXMINUSTYY                 1109
#define IDC_TYZ                         1110
#define IDC_TZX                         1111
#define IDC_TXY                         1112
#define IDC_VALOROBSERVADO              1113
#define IDC_LCREPORT                    1114
#define IDC_ERROR                       1115
#define IDC_LIMITE                      1116
#define IDC_EJEX1                       1116
#define IDC_VALORES                     1117
#define IDC_EJEY1                       1117
#define IDC_EJEZ1                       1118
#define IDC_EJEX2                       1119
#define IDC_EJEY2                       1120
#define IDC_EJEZ2                       1121
#define ID_INSERTAR_BIFENIL             32774
#define ID_INSERTAR_TRIFENIL            32775
#define ID_ARCHIVO_PROPIEDADES          32776
#define ID_ARCHIVO_PREPARARPAGINA       32777
#define ID_VIEW_AXIS                    32778
#define ID_AXIS_X                       32779
#define ID_AXIS_Y                       32780
#define ID_AXIS_Z                       32781
#define ID_ROTATE_POSITIVE              32782
#define ID_ROTATE_NEGATIVE              32783
#define ID_APPROACH                     32784
#define ID_SEPARATE                     32785
#define ID_PCYLINDER                    32786
#define ID_PSPHERE                      32787
#define ID_VER_GDI                      32788
#define ID_VER_OPENGL                   32789
#define ID_ANILLOFENIL_ELIMINAR         32790
#define ID_ANILLOFENIL_ANGULOS_EXTERNOS 32791
#define ID_ANILLOFENIL_ANGULOS_INTERNOS 32792
#define ID_ANILLOFENIL_LADOS_EXTERNOS   32793
#define ID_ANILLOFENIL_LADOS_INTERNOS   32794
#define ID_ANILLOFENIL_INFORMACION      32795
#define ID_BIFENIL_ELIMINAR             32796
#define ID_BIFENIL_ANGULOS              32797
#define ID_BIFENIL_LADOS                32798
#define ID_BIFENIL_INFORMACION          32799
#define ID_TRIFENIL_ELIMINAR            32800
#define ID_TRIFENIL_INFORMACION         32801
#define ID_TRIFENIL_ANGULOS_EXTERNOS    32802
#define ID_TRIFENIL_ANGULOS_INTERNOS    32803
#define ID_TRIFENIL_LADOS_EXTERNOS      32804
#define ID_TRIFENIL_LADOS_INTERNOS      32805
#define ID_TRIFENIL_ANGULOS             32806
#define ID_TRIFENIL_LADOS               32807
#define ID_TRIFENIL_BRAZO               32808
#define ID_ANILLOFENIL_EJEROTACION      32809
#define ID_BIFENIL_EJEROTACION          32810
#define ID_TRIFENIL_EJEROTACION         32811
#define ID_INSERTAR_INTERACOBS          32812
#define ID_BUTTON32865                  32813
#define ID_INSERTAR_INTERACCOMP         32814
#define ID_BUTTON32870                  32815
#define ID_EDITAR_REPETIR               32816
#define ID_EDITAR_BORRAR                32817
#define ID_INSERTAR_ANILLO              32818
#define ID_INSERTAR_VARIABLES           32819
#define ID_CALCULAR_BARRIDO             32820
#define ID_CALCULAR_COMBDADA            32821
#define ID_OPCIONES_DATOS3D             32822
#define ID_OPCIONES_PREFERENCIAS        32823
#define ID_OPCIONES_REPORTES_CONFORMAC  32824
#define ID_VER_BARRA3D                  32825
#define ID_VER_BARRAPARTES              32826
#define ID_VER_CUADRICULA               32827
#define ID_VER_LISTAPARTES              32828
#define ID_VER_LISTARESULTADOS          32829
#define ID_VER_BARRAPRINCIPAL           32830
#define ID_FILE_NUEVO                   32908
#define ID_FILE_ABRIR                   32909
#define ID_ARCHIVO_CERRAR               32910
#define ID_3D_EJECUTAR                  32915
#define ID_INSERTAR_INTERACCIONESDEDISTORCION 32916
#define ID_OPCIONES_REPORTES_RESULTSFINAL 32919
#define ID_OPCIONES_REPORTES_RESULTSXERROR 32921
#define ID_OPCIONES_REPORTES_RESULTSXMAD 32922
#define ID_OPCIONES_CALCULO             32923
#define ID_TRIFENIL_ANGULOS_ANGULOSALEJEDEPROYECCION 32924
#define ID_TRIFENIL_ANGULOS_ANGULOSENTRELOSLADOS 32925
#define ID_OPCIONES_EJEDESIMETRA        32926
#define AFX_IDS_HELPMODEMESSAGE2        57348
#define AFX_IDS_HELPMODEMESSAGE3        57351
#define ID_OBJECTS_FIND                 61207
#define IDC_MAINBAR_BOX                 61208
#define IDC_PARTESLIST1                 61209
#define IDS_RESULTSONESHT_CAPTION       61210

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        224
#define _APS_NEXT_COMMAND_VALUE         32927
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           134
#endif
#endif
